Homework 3
nikonsok/PY_HW pull request #4
Opened 2023-03-16 04:32 UTC by nikonsok

Hw3.1 - Не смог пройти тесты (не видят файл data.txt, разобраться вообще не получилось)
Hw3.2 - Всё ок по тестам
Hw3.3 - тут я попросту сдался уже (Не понимаю как передать значения в функцию  range(), чтобы она возвращалась основной функцией (оставил самый простой пример входных данных)

2023-03-16 18:23 UTC, alpakhomov requested changes
Оставил комменты + заданий в этой домашке 4

2023-03-16 18:23 UTC, alpakhomov commented on hw3/hw_3_1.py
> +                if not failed:
нам не нужно ничего писать в файл с ошибками если ошибки нет; флаг failed тоже соответственно не нужен

2023-03-16 18:23 UTC, alpakhomov commented on hw3/hw_3_1.py
> +    return re.match('^\d{4}-\d{2}-\d{2}$', date)
https://docs.python.org/3/library/re.html#search-vs-match

1. Матч возвращает не bool. Если нужен bool, нужно кастить тип явно `bool(re.match...)`
2. Match в питоне устроен странно. Он матчит только если строка совпадает сначала. Можно либо изменить регулярку, либо использовать re.search (регулярка все равно содержит ошибку, первый символ `^` не нужен)

2023-03-16 18:23 UTC, alpakhomov commented on hw3/test_hw_3_2.py
> +    assert val_1 is val_2
```py
assert all((val_1, val_2))
```
Если добавить такую строку, то тест не будет проходить - потому что в решении сейчас ничего не вычисляется, значения всегда None

2023-03-26 21:40 UTC, nikonsok commented on hw3/hw_3_1.py
> +                if not failed:
В задании есть вот такой пункт для выполнения:
 write a report to txt file and return absolute path to that file. For each line you should report 
it if it doesn't conform with at least one rule, plus add a reason - the name of a validator that
doesn't pass (if there are more than one failed rules, get the name of the first one that fails)
Я правильно понимаю, что нужно писать отчёт в файл data.txt? (То есть добавлять в строке с не валидными данными имя упавшего валидатора)

2023-03-29 00:25 UTC, merged